[package]
name = "BrioschenBot"
version = "0.1.0"
authors = ["Torben Lehmann <torben.leh@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
telegram-client = "1.6.2"
rtdlib = "1.6.4"
serde_json = "1.0.59"